name: Resyntax

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          version: stable
          catalogs: https://pkg-build.racket-lang.org/server/built/catalog/
      - run: sudo raco pkg install --auto --installation --batch --binary-lib resyntax
      - run: sudo raco pkg install --auto --installation https://github.com/jackfirth/resyntax.git#feature-github-integration
      - run: resyntax analyze --local-git-repository . "${GITHUB_BASE_REF}" --output-as-github-review
