name: Resyntax

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          version: stable
      - run: raco pkg install --auto --no-docs https://github.com/jackfirth/resyntax.git#feature-github-integration
      - run: echo xvfb-run racket -l- resyntax/cli analyze --local-git-repository . "${GITHUB_BASE_REF}" --output-as-github-review
      - run: git remote
      - run: xvfb-run racket -l- resyntax/cli analyze --local-git-repository . "${GITHUB_BASE_REF}" --output-as-github-review
